# Generated by Django 3.1 on 2020-09-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.TextField()),
                ('name', models.TextField()),
                ('alcohol_type', models.TextField()),
                ('tag', models.TextField()),
                ('alcohol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('food', models.TextField()),
                ('img', models.TextField()),
                ('tag', models.TextField()),
                ('material', models.TextField()),
                ('cooking_time', models.TextField()),
                ('scrap', models.TextField()),
            ],
        ),
    ]
